
services:
  mysql-db:
    image: mysql:8.0
    container_name: compemanage_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456        # 设置数据库的 root 密码（此处设为 root）
      MYSQL_DATABASE: CompeManage        # 与你 config.go 中的默认 DB_NAME 保持一致
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"                      # 映射到你本地的 3306 端口
    volumes:
      - ./mysql_data:/var/lib/mysql      # 数据持久化目录
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: compemanage-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data   # 使用下方声明的命名数据卷
    command: redis-server --appendonly yes # 开启 AOF 持久化

volumes:
  redis_data: 