services:
  app:
    image: ywxx252324/compemanage:latest
    container_name: compemanage_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Shanghai
      - APP_ENV=production
      - JWT_SECRET=4c8b2a9e7f1d3c6a5b0e8d9f2c1a4b7e6d3f0c9a8b5e2d1f4c7a0b9e6d3f2c1a
      - CAS_CLIENT_ID=compemanage
      - CAS_CLIENT_SECRET=compemanage
      - CAS_REDIRECT_URI=https://xkjs.gzhu.edu.cn/api/cas/callback
      - CAS_FRONTEND_URL=https://xkjs.gzhu.edu.cn
    depends_on:
      - mysql-db
      - redis

  mysql-db:
    image: mysql:8.0
    container_name: compemanage_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: CompeManage
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:latest
    container_name: compemanage-redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: