database:
  host: "compemanage_mysql"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "CompeManage"

redis:
  host: "compemanage-redis"
  port: 6379
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10

logger:
  level: "info"
  filename: logs/prod.log
  max_size: 100
  max_backups: 30
  max_age: 30
  compress: true
  show_line: false

datahall:
  key: "2026051118227ee8fb684d1211f18e4a0a3e580ef7931655"
  secret: "bd6d57fc3e95940c974fb7b37c9ff4d0fe6a7911"
  base_url: "https://datahall.gzhu.edu.cn"
  min_grade: "2022"
